config/routes.rb
Rails.application.routes.draw do
  resources :plants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  before_save :set_watered_at, :set_fed_at, :set_growth

  def needs_water?
    return 'Yes' if self.watered_at <= 5.minutes.ago
    'No'
  end

  def needs_food?
    return 'Yes' if self.fed_at <= 10.minutes.ago
    'No'
  end

  def set_watered_at
    self.watered_at = Time.now if self.water_amount
  end

  def set_fed_at
    self.fed_at = Time.now if self.fed_amount
  end

  def set_growth
    self.growth = water_amount.to_i + fed_amount.to_i
  end

  def age
    if growth == 0
      'baby'
    elsif growth > 0 && growth < 20
      'young adult'
    elsif growth >= 20
      'full grown'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :water_amount, :fed_amount, :growth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :water_amount %>
    <%= form.number_field :water_amount, min: 1, max: 30 %>
  </div>

  <div class="field">
    <%= form.label :fed_amount %>
    <%= form.number_field :fed_amount, min: 1, max: 30 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plant Pets
  <img src='/assets/plant.png' height='50' width='50' />
</h1>

<table id='plants'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Water</th>
      <th>Needs Water?</th>
      <th>Fed</th>
      <th>Needs Food?</th>
      <th>Age</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.water_amount %></td>
        <td><%= plant.needs_water?%></td>
        <td><%= plant.fed_amount %></td>
        <td><%= plant.needs_food? %></td>
        <td><%= plant.age %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Plant Pet
  <img src='/assets/plant.png' height='100' width='100' />
</h1>
<hr/>
<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Needs Water:</strong>
  <%= @plant.needs_water? %>
</p>

<p>
  <strong>Water:</strong>
  <%= @plant.water_amount %>
</p>

<p>
  <strong>Needs Food:</strong>
  <%= @plant.needs_food? %>
</p>

<p>
  <strong>Food:</strong>
  <%= @plant.fed_amount %>
</p>

<p>
  <strong>Age:</strong>
  <%= @plant.age %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>